#! /bin/sh
#
# This is an init script for openembedded
# Copy it to /etc/init.d/rsc and type
# > update-rc.d rsc defaults 80 30
#

PATH=/bin:/usr/bin:/sbin:/usr/sbin

name="rsc"
daemon="/usr/sbin/${name}"
pidfile="/var/run/${name}.pid"
defaults="/etc/default/${name}"
args=""

# Exit if the daemon is not installed
test -x "${daemon}" || exit 0

# Load default settings
[ -f ${defaults} ] && . ${defaults}

# Build up the command-line arguments
args="${args} -D"

if [ -n "${PIDFILE_PATH}" ]; then
    pidfile="${PIDFILE_PATH}"
fi
args="${args} --pidfile ${pidfile}"

# Peform the action
case "$1" in
  start)
    echo -n "Starting ${name}"
    start-stop-daemon --start --quiet --pidfile ${pidfile} --exec ${daemon} -- ${args}
    echo "."
    ;;
  stop)
    echo -n "Stopping ${name}"
    start-stop-daemon --stop --quiet --pidfile ${pidfile} --exec ${daemon}
    echo "."
    ;;
  reload|force-reload)
    start-stop-daemon --stop --quiet --pidfile ${pidfile} -signal 1 --exec ${daemon}
    ;;
  restart)
    echo -n "Stopping ${name}"
    start-stop-daemon --stop --quiet --pidfile ${pidfile} --exec ${daemon}
    echo ""
    echo -n "Waiting for ${name} process to die off"
    for i in 1 2 3 ;
    do
        sleep 1
        echo -n "."
    done
    echo ""
    echo -n "Starting ${name}"
    start-stop-daemon --start --quiet --pidfile ${pidfile} --exec ${daemon} -- ${args}
    echo "."
    ;;
  *)
    echo "Usage: /etc/init.d/${name} {start|stop|reload|restart|force-reload}"
    exit 1
esac

exit 0
